#!/bin/sh

export PATH=$PATH:$PWD/bin
#export RUBYLIB=$RUBYLIB:$PWD/lib
#export CLASSPATH=$CLASSPATH:$PWD/classes:$PWD/fig.jar

# Go to an exec (assume either in run directory or another exec directory)
ge() {
  if basename $PWD | grep -q exec; then x=`dirname $PWD`
  elif [ `basename $PWD` == "e" ]; then x=.
  else                                  x=e
  fi
  cd $x/$1.exec
}
# Go to last modified exec
gel() {
  if basename $PWD | grep -q exec; then x=`dirname $PWD`
  elif [ `basename $PWD` == "e" ]; then x=.
  else                                  x=e
  fi
  cd `/bin/ls -d -t $x/*.exec | head -1`
}
